In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
#Set root correctly...
os.chdir(r"C:\Users\jamed\Documents\repos\lidar_2\LidarClassifcationForFloodModelling")

In [3]:
from RandLANetImplementation.data import modelData

In [4]:
model_data = modelData()

In [ ]:
model_data.new_split()

tensor([ 139499,  139502,  139503,  ..., 6163672, 6163673, 6163674])
tensor([    9841,     9842,     9843,  ..., 13127398, 13127399, 13127400])
<class 'torch.Tensor'>


[tensor([       0,        1,        2,  ..., 10331714, 10332454, 10332455]),
 tensor([ 2668649,  2668650,  2668651,  ..., 15263430, 15263431, 15263432]),
 tensor([ 9968889,  9968890,  9968891,  ..., 15263185, 15263186, 15263187]),
 tensor([   2466,    2508,    2552,  ..., 9957769, 9957770, 9957771]),
 tensor([     913,      914,      915,  ..., 15263581, 15263582, 15263583])]

In [ ]:
folds = model_data.get_folds()