In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
#run from repo root...
os.chdir(r"C:/Users/jamed\Documents/repos/lidar_2/LidarClassifcationForFloodModelling")

In [3]:
from structured_data_utils.data import ModelData

KeyboardInterrupt: 

In [ ]:
data = ModelData()

In [ ]:
data.prepare_data()

12642.0
tensor([[[False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         [False, False, False,  ...,  True,  True,  True],
         ...,
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True],
         [ True,  True,  True,  ...,  True,  True,  True]]])
starting
ending
torch.Size([2438, 300, 300])
tensor([1., 1., 1.,  ..., 0., 0., 0.])
torch.Size([355, 300, 300])


In [ ]:
data.prepare_train_test()

In [ ]:
print(data.train_set.data.shape)
print(data.test_set.data.shape)
print(data.segmented_data_with_labels.data.shape)

torch.Size([35, 300, 300])
torch.Size([34, 300, 300])
torch.Size([69, 300, 300])


In [ ]:
data.train_set.data

tensor([[[17.4629, 17.4383, 17.4162,  ..., 20.3024, 20.2089, 20.1466],
         [17.5749, 17.5623, 17.5213,  ..., 20.2189, 20.1497, 20.0978],
         [17.7122, 17.7198, 17.6751,  ..., 20.1021, 20.1043, 20.0918],
         ...,
         [17.6419, 17.7433, 17.9280,  ..., 18.5426, 18.5530, 18.5658],
         [17.8164, 17.8540, 17.9095,  ..., 18.5530, 18.5646, 18.5786],
         [17.8614, 17.8795, 17.8891,  ..., 18.5589, 18.5712, 18.5854]],

        [[20.1157, 20.1138, 20.1410,  ..., 23.6660, 23.6749, 23.6483],
         [20.0631, 20.0517, 20.0637,  ..., 23.6403, 23.6626, 23.6632],
         [20.0647, 20.0374, 20.0100,  ..., 23.5925, 23.6061, 23.6154],
         ...,
         [18.5807, 18.5915, 18.5979,  ..., 20.2324, 20.2420, 20.2543],
         [18.5951, 18.6079, 18.6170,  ..., 20.2353, 20.2456, 20.2568],
         [18.6012, 18.6142, 18.6242,  ..., 20.2411, 20.2510, 20.2612]],

        [[23.5412, 24.9013, 27.0254,  ..., 12.7023, 12.7008, 12.7042],
         [21.6741, 23.2422, 25.8991,  ..., 12

In [ ]:
print(data.test_set.data.shape)
print(data.test_set.labels.shape)

torch.Size([34, 300, 300])
torch.Size([34, 300, 300])
